# MkDocs設定ファイル
site_name: WebRTC Agent Documentation
site_description: WebRTC-based AI agent for system development consultation
site_author: WebRTC Agent Team
site_url: https://zawakichi.github.io/webrtc-agent

# リポジトリ情報
repo_name: zawakichi/webrtc-agent
repo_url: https://github.com/zawakichi/webrtc-agent
edit_uri: edit/main/doc/

# ディレクトリ設定
docs_dir: docs
site_dir: site

# テーマ設定
theme:
  name: material
  language: ja
  palette:
    # ライトモード
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    # ダークモード
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.action.edit

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# プラグイン
plugins:
  - search:
      lang: ja
  - awesome-pages
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Tokyo
      locale: ja
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - macros
  - mermaid2:
      arguments:
        theme: 'base'
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'
          primaryBorderColor: '#1976d2'

# マークダウン拡張
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: 目次
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: zawakichi
      repo: webrtc-agent
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# ナビゲーション構造
nav:
  - ホーム: index.md
  - プロジェクト企画:
    - エレベーターピッチ: pitch/elevator-pitch.md
  - 要件定義:
    - 形式的要件定義: requirements/formal-requirements.md
    - ステークホルダー分析: requirements/stakeholder-analysis.md
  - 仕様:
    - システム仕様: specifications/SPECIFICATIONS.md
    - MVP定義: specifications/mvp-definition.md
  - アーキテクチャ:
    - architecture/index.md
    - クリーンアーキテクチャ: architecture/clean-architecture.md
    - データベース設計: architecture/database-design.md
    - BDDテスト戦略: architecture/bdd-test-strategy.md
  - 開発ガイド:
    - development/index.md
    - インクリメンタル計画: development/incremental-plan.md
    - セットアップ: development/setup.md
    - 開発フロー: development/workflow.md
    - テスト: development/testing.md
  - API:
    - api/index.md
    - REST API: api/rest.md
    - WebSocket API: api/websocket.md
    - WebRTC API: api/webrtc.md
  - デプロイ:
    - deployment/index.md
    - Docker: deployment/docker.md
    - Kubernetes: deployment/kubernetes.md
    - CI/CD: deployment/cicd.md
  - 統合管理:
    - トレーサビリティマトリックス: integration/traceability-matrix.md
    - 最終統合レポート: integration/final-integration-report.md

# 追加CSS
extra_css:
  - stylesheets/extra.css

# 追加JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# その他設定
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zawakichi/webrtc-agent
  version:
    provider: mike

# 著作権
copyright: Copyright &copy; zawaqkichi 2025